
let authMode='login',currentUser=null,currentSpace=null,profile=null,items=[],anniversaries=[],reflections={},filter='all',newestFirst=true,tempPhotos=[],realtimeChannel=null,map=null,mapMarkers=[];
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function show(el){el?.classList.remove('hidden')}function hide(el){el?.classList.add('hidden')}function msg(el,text,isError=false){if(!el)return;el.textContent=text||'';el.classList.toggle('error',!!isError)}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
function today(){return new Date().toISOString().slice(0,10)}function formatDate(v){if(!v)return'';const d=new Date(v+'T00:00:00');return `${d.getFullYear()}/${d.getMonth()+1}/${d.getDate()}`}
function safeFileName(name){return name.normalize('NFKD').replace(/[^a-zA-Z0-9._-]/g,'_').slice(-80)||'photo.jpg'}function norm(s){return(s||'').toLowerCase().replace(/[\s　・!！?？,，.。]/g,'')}
function monthKey(v){if(!v)return'';const d=new Date(v+'T00:00:00');return `${d.getFullYear()}年${d.getMonth()+1}月`}

async function bootstrap(){
 if(!configured){show($('#configWarning'));return}
 const{data}=await sb.auth.getSession();currentUser=data.session?.user||null;if(currentUser)await afterLogin();
 sb.auth.onAuthStateChange(async(_event,session)=>{const next=session?.user||null;if(next?.id!==currentUser?.id){currentUser=next;if(currentUser)await afterLogin();else showAuth()}})
}
function showAuth(){currentSpace=null;items=[];anniversaries=[];reflections={};if(realtimeChannel){sb.removeChannel(realtimeChannel);realtimeChannel=null}show($('#authScreen'));hide($('#pairScreen'));hide($('#app'))}
async function afterLogin(){hide($('#authScreen'));$('#accountEmail').textContent=currentUser.email||'';const membership=await getMembership();if(!membership){show($('#pairScreen'));hide($('#app'));return}currentSpace=membership;hide($('#pairScreen'));show($('#app'));$('#inviteCodeText').textContent=currentSpace.invite_code;await Promise.all([loadProfile(),loadItems(),loadAnniversaries(),loadReflections()]);subscribeRealtime();renderAll()}
async function getMembership(){const{data:member,error}=await sb.from('couple_members').select('space_id').eq('user_id',currentUser.id).maybeSingle();if(error||!member)return null;const{data:space}=await sb.from('couple_spaces').select('id,name,invite_code').eq('id',member.space_id).single();return space||null}
async function loadProfile(){const{data}=await sb.from('couple_profiles').select('*').eq('space_id',currentSpace.id).eq('user_id',currentUser.id).maybeSingle();profile=data||{display_name:'',area_preference:''};$('#displayNameInput').value=profile.display_name||'';$('#areaPreferenceInput').value=profile.area_preference||''}
async function loadItems(){const{data,error}=await sb.from('bucket_items').select('*').eq('space_id',currentSpace.id).order('created_at',{ascending:false});if(error){console.error(error);return}items=await Promise.all((data||[]).map(hydrateItem))}
async function hydrateItem(row){const photos=[];for(const path of(row.photo_paths||[])){const{data}=await sb.storage.from('memories').createSignedUrl(path,3600);photos.push({path,url:data?.signedUrl||''})}return{id:row.id,title:row.title,category:row.category,date:row.planned_date||'',place:row.place||'',note:row.note||'',done:row.done,completedDate:row.completed_date||'',memoryNote:row.memory_note||'',photos,createdBy:row.created_by,createdAt:new Date(row.created_at).getTime(),updatedAt:new Date(row.updated_at).getTime(),favorite:!!row.favorite,lat:row.latitude,long:row.longitude}}
async function loadAnniversaries(){const{data,error}=await sb.from('anniversaries').select('*').eq('space_id',currentSpace.id).order('date',{ascending:true});if(error){console.error('loadAnniversaries',error);toast('記念日の読み込みに失敗しました');return}anniversaries=data||[]}
async function loadReflections(){const{data}=await sb.from('memory_reflections').select('*').eq('space_id',currentSpace.id);reflections={};(data||[]).forEach(r=>{if(!reflections[r.item_id])reflections[r.item_id]=[];reflections[r.item_id].push(r)})}
function subscribeRealtime(){if(realtimeChannel)sb.removeChannel(realtimeChannel);realtimeChannel=sb.channel(`couple-${currentSpace.id}`).on('postgres_changes',{event:'*',schema:'public',table:'bucket_items',filter:`space_id=eq.${currentSpace.id}`},refreshData).on('postgres_changes',{event:'*',schema:'public',table:'anniversaries',filter:`space_id=eq.${currentSpace.id}`},refreshData).on('postgres_changes',{event:'*',schema:'public',table:'memory_reflections',filter:`space_id=eq.${currentSpace.id}`},refreshData).subscribe()}
async function refreshData(){await Promise.all([loadItems(),loadAnniversaries(),loadReflections()]);renderAll()}
function renderAll(){renderWishlist();renderHome();renderTimeline();renderMap();renderRecap()}

function gotoPage(name){$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.pageTarget===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='map')setTimeout(()=>map?.invalidateSize(),50)}
$$('.nav-item').forEach(b=>b.onclick=()=>gotoPage(b.dataset.pageTarget));$$('[data-goto]').forEach(b=>b.onclick=()=>gotoPage(b.dataset.goto));

function renderHome(){
 $('#homeSpaceName').textContent=currentSpace?.name||'';const done=items.filter(i=>i.done);$('#homeDoneCount').textContent=done.length;$('#homeMemoryCount').textContent=done.filter(i=>i.memoryNote||i.photos.length).length;$('#homePhotoCount').textContent=done.reduce((n,i)=>n+i.photos.length,0);
 const h=new Date().getHours();$('#homeGreeting').textContent=h<11?'おはよう。次はどこへ行く？':h<17?'今日も、ふたりの楽しみを増やそう。':'今日の思い出も、ここに残そう。';renderNextAnniversary();renderRecommendations();renderNextTodos();renderRecentMemories();
}
function nextAnniversaryInfo(a){const now=new Date();now.setHours(0,0,0,0);let d=new Date(a.date+'T00:00:00');if(a.repeat_type==='yearly'){d=new Date(now.getFullYear(),d.getMonth(),d.getDate());if(d<now)d=new Date(now.getFullYear()+1,d.getMonth(),d.getDate())}const days=Math.ceil((d-now)/86400000);return{date:d,days}}
function renderNextAnniversary(){const el=$('#nextAnniversaryCard'),list=$('#anniversaryList');list.innerHTML='';if(!anniversaries.length){el.className='anniversary-card empty-soft';el.innerHTML='<span class="big-emoji">🎀</span><div><strong>記念日を登録しよう</strong><p>付き合った日、誕生日、初旅行など</p></div>';el.onclick=null;return}const enriched=anniversaries.map(a=>({...a,...nextAnniversaryInfo(a)}));const upcoming=enriched.filter(a=>a.days>=0).sort((a,b)=>a.days-b.days);const a=upcoming[0]||enriched.sort((a,b)=>Math.abs(a.days)-Math.abs(b.days))[0];el.className='anniversary-card';const countdown=a.days>=0?`あと ${a.days} 日`:`${Math.abs(a.days)} 日前`;el.innerHTML=`<span class="big-emoji">💐</span><div><strong>${escapeHtml(a.title)}</strong><p>${a.date.replaceAll('-','/')}</p><div class="countdown">${countdown}</div></div>`;el.onclick=()=>openAnniversary(a.id);enriched.sort((a,b)=>a.date.localeCompare(b.date)).forEach(x=>{const row=document.createElement('button');row.type='button';row.className='anniversary-mini'+(x.days<0?' past':'');const d=x.days>=0?`あと ${x.days}日`:`${Math.abs(x.days)}日前`;row.innerHTML=`<span class="icon">🎀</span><span><strong>${escapeHtml(x.title)}</strong><p>${x.date.replaceAll('-','/')} · ${x.repeat_type==='yearly'?'毎年':'1回'}</p></span><span class="days">${d}</span>`;row.onclick=()=>openAnniversary(x.id);list.appendChild(row)})}
function getRecommendations(){const currentMonth=new Date().getMonth()+1;const existing=items.map(i=>norm(i.title+' '+i.place+' '+i.note)).join('|');let pool=recommendations.filter(r=>!existing.includes(norm(r.title))&&!r.tags.some(t=>existing.includes(norm(t)))&&r.months.includes(currentMonth));if(pool.length<8)pool=[...pool,...recommendations.filter(r=>!pool.includes(r)&&!existing.includes(norm(r.title)))];return shuffle(pool).slice(0,6)}
function shuffle(a){return[...a].sort(()=>Math.random()-.5)}
function renderRecommendations(){const wrap=$('#recommendationList');wrap.innerHTML='';getRecommendations().forEach((r,idx)=>{const card=document.createElement('article');card.className='recommend-card';card.style.setProperty('--bubble',['#ffe6ee','#fff0d5','#e9f1df','#eee8fa'][idx%4]);const area=profile?.area_preference?`おすすめエリア: ${profile.area_preference}`:'季節に合う候補';card.innerHTML=`<div class="emoji">${r.emoji}</div><h3>${escapeHtml(r.title)}</h3><p class="recommend-meta">${escapeHtml(area)}</p><p>${escapeHtml(r.desc)}</p><button type="button">♡ やりたいに追加</button>`;card.querySelector('button').onclick=()=>addRecommendation(r);wrap.appendChild(card)})}
async function addRecommendation(r){const payload={space_id:currentSpace.id,created_by:currentUser.id,title:r.title,category:r.category,place:r.place,note:'おすすめから追加'};const{error}=await sb.from('bucket_items').insert(payload);if(error)return toast('追加できませんでした');toast('やりたいことに追加しました ♡');await refreshData()}
function renderNextTodos(){const wrap=$('#nextTodoList');wrap.innerHTML='';const list=items.filter(i=>!i.done).sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')).slice(0,3);if(!list.length){wrap.innerHTML='<div class="mini-card"><div class="mini-icon">♡</div><div><strong>次のやりたいことを追加しよう</strong><p>おすすめから追加するのもOK</p></div></div>';return}list.forEach(i=>{const c=document.createElement('div');c.className='mini-card';c.innerHTML=`<div class="mini-icon">${categoryEmoji[i.category]||'♡'}</div><div><strong>${escapeHtml(i.title)}</strong><p>${escapeHtml(i.place||categoryNames[i.category])}</p></div><span class="arrow">›</span>`;c.onclick=()=>openEditor(i.id);wrap.appendChild(c)})}
function renderRecentMemories(){renderMemoryTiles($('#recentMemoryList'),items.filter(i=>i.done).sort((a,b)=>(b.completedDate||'').localeCompare(a.completedDate||'')).slice(0,4))}
function renderMemoryTiles(wrap,list){wrap.innerHTML='';if(!list.length){wrap.innerHTML='<div class="mini-card" style="grid-column:1/-1"><div class="mini-icon">📷</div><div><strong>思い出はこれから</strong><p>「できた！」にするとここに増えていきます</p></div></div>';return}list.forEach(i=>{const el=document.createElement('article');el.className='memory-tile';el.innerHTML=i.photos[0]?.url?`<img src="${i.photos[0].url}" alt="">`:`<div class="fallback">${categoryEmoji[i.category]||'♡'}</div>`;const d=document.createElement('div');d.innerHTML=`<strong>${escapeHtml(i.title)}${i.favorite?' <span class="favorite-mark">♥</span>':''}</strong><small>${formatDate(i.completedDate)}</small>`;el.appendChild(d);el.onclick=()=>openMemory(i.id);wrap.appendChild(el)})}
