
// Auth
if(!configured)show($('#configWarning'));
$$('.auth-tab').forEach(btn=>btn.onclick=()=>{authMode=btn.dataset.authTab;$$('.auth-tab').forEach(x=>x.classList.toggle('active',x===btn));$('#authSubmit').textContent=authMode==='login'?'ログイン':'アカウントを作る';$('#passwordInput').autocomplete=authMode==='login'?'current-password':'new-password';msg($('#authMessage'),'')});
$('#authForm').onsubmit=async e=>{e.preventDefault();if(!configured)return;const email=$('#emailInput').value.trim(),password=$('#passwordInput').value;$('#authSubmit').disabled=true;msg($('#authMessage'),'処理中…');const res=authMode==='login'?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password,options:{emailRedirectTo:location.href.split('#')[0]}});$('#authSubmit').disabled=false;if(res.error)return msg($('#authMessage'),res.error.message,true);if(authMode==='signup'&&!res.data.session)msg($('#authMessage'),'確認メールを送りました。メール内リンクを開いてからログインしてください。');else msg($('#authMessage'),'')};
$('#createSpaceBtn').onclick=async()=>{msg($('#pairMessage'),'作成中…');const{error}=await sb.rpc('create_couple_space',{space_name:$('#spaceNameInput').value.trim()||'ふたり日和'});if(error)return msg($('#pairMessage'),error.message,true);await afterLogin();toast('ふたりのページを作成しました ♡')};
$('#joinSpaceBtn').onclick=async()=>{const code=$('#inviteInput').value.trim().toUpperCase();if(code.length!==8)return msg($('#pairMessage'),'8文字の招待コードを入力してください。',true);const{error}=await sb.rpc('join_couple_space',{code});if(error)return msg($('#pairMessage'),'コードが違うか、すでに2人参加しています。',true);await afterLogin();toast('ふたりのページに参加しました ♡')};$('#pairLogoutBtn').onclick=()=>sb.auth.signOut();

// Wishlist
$('#addBtn').onclick=()=>openEditor();$('#closeDialog').onclick=()=>$('#itemDialog').close();$('#closeMemory').onclick=()=>$('#memoryDialog').close();
$('#itemForm').onsubmit=async e=>{e.preventDefault();const id=$('#itemId').value;const place=$('#placeInput').value.trim();let geo=id?(()=>{const i=items.find(x=>x.id===id);return i?.place===place&&i.lat?{lat:i.lat,long:i.long}:null})():null;if(place&&!geo){$('#syncStatus').textContent='● 場所を確認中…';geo=await geocodePlace(place)}const payload={title:$('#titleInput').value.trim(),category:$('#categoryInput').value,planned_date:$('#dateInput').value||null,place,note:$('#noteInput').value.trim(),latitude:geo?.lat||null,longitude:geo?.long||null};let error;if(id)({error}=await sb.from('bucket_items').update(payload).eq('id',id));else({error}=await sb.from('bucket_items').insert({...payload,space_id:currentSpace.id,created_by:currentUser.id}));if(error)return toast('保存できませんでした');$('#itemDialog').close();await refreshData();toast(id?'更新しました':'追加しました ♡')};
$('#deleteBtn').onclick=async()=>{const id=$('#itemId').value;if(!id||!confirm('この項目を削除しますか？'))return;const i=items.find(x=>x.id===id),paths=(i?.photos||[]).map(p=>p.path);if(paths.length)await sb.storage.from('memories').remove(paths);const{error}=await sb.from('bucket_items').delete().eq('id',id);if(error)return toast('削除できませんでした');$('#itemDialog').close();await refreshData();toast('削除しました')};
$('#photoInput').onchange=e=>{[...e.target.files].forEach(file=>{if(tempPhotos.length<8)tempPhotos.push({type:'new',file,url:URL.createObjectURL(file)})});renderPhotoPreview();e.target.value=''};
$('#memoryForm').onsubmit=async e=>{e.preventDefault();const id=$('#memoryItemId').value,i=items.find(x=>x.id===id);if(!i)return;const original=(i.photos||[]).map(p=>p.path);let paths;try{paths=await uploadNewPhotos(id)}catch(err){console.error(err);return toast('写真のアップロードに失敗しました')}const{error}=await sb.from('bucket_items').update({done:true,completed_date:$('#completedDateInput').value||today(),memory_note:$('#memoryNoteInput').value.trim(),photo_paths:paths,favorite:$('#favoriteInput').checked}).eq('id',id);if(error)return toast('思い出を保存できませんでした');const reflection=$('#myReflectionInput').value.trim();if(reflection){await sb.from('memory_reflections').upsert({space_id:currentSpace.id,item_id:id,user_id:currentUser.id,display_name:profile?.display_name||'わたし',reflection},{onConflict:'item_id,user_id'})}else{await sb.from('memory_reflections').delete().eq('item_id',id).eq('user_id',currentUser.id)}await removeDeletedPhotos(original,paths);$('#memoryDialog').close();await refreshData();toast('思い出を保存しました ♡')};
$('#searchInput').oninput=renderWishlist;$('#filterChips').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;$$('.chip').forEach(x=>x.classList.toggle('active',x===b));renderWishlist()};$('#sortBtn').onclick=()=>{newestFirst=!newestFirst;$('#sortBtn').textContent=newestFirst?'↕ 新しい順':'↕ 古い順';renderWishlist()};

// Anniversary
$('#addAnniversaryBtn').onclick=()=>openAnniversary();$('#closeAnniversary').onclick=()=>$('#anniversaryDialog').close();
$('#anniversaryForm').onsubmit=async e=>{e.preventDefault();const id=$('#anniversaryId').value,payload={space_id:currentSpace.id,title:$('#anniversaryTitle').value.trim(),date:$('#anniversaryDate').value,repeat_type:$('#anniversaryRepeat').value,created_by:currentUser.id};let result;if(id)result=await sb.from('anniversaries').update(payload).eq('id',id).select().single();else result=await sb.from('anniversaries').insert(payload).select().single();if(result.error){console.error('anniversary save',result.error);return toast('記念日を保存できませんでした: '+result.error.message)}$('#anniversaryDialog').close();await loadAnniversaries();renderHome();toast('記念日を保存しました 🎀（現在 '+anniversaries.length+'件）')};
$('#deleteAnniversary').onclick=async()=>{const id=$('#anniversaryId').value;if(!id||!confirm('この記念日を削除しますか？'))return;await sb.from('anniversaries').delete().eq('id',id);$('#anniversaryDialog').close();await loadAnniversaries();renderHome()};

// Settings
$('#settingsBtn').onclick=()=>$('#settingsDialog').showModal();$('#closeSettings').onclick=()=>$('#settingsDialog').close();$('#logoutBtn').onclick=async()=>{$('#settingsDialog').close();await sb.auth.signOut()};$('#copyInviteBtn').onclick=async()=>{try{await navigator.clipboard.writeText(currentSpace.invite_code);toast('招待コードをコピーしました')}catch{toast(`招待コード: ${currentSpace.invite_code}`)}};
$('#saveProfileBtn').onclick=async()=>{const payload={space_id:currentSpace.id,user_id:currentUser.id,display_name:$('#displayNameInput').value.trim(),area_preference:$('#areaPreferenceInput').value.trim()};const{error}=await sb.from('couple_profiles').upsert(payload,{onConflict:'space_id,user_id'});if(error)return toast('設定を保存できませんでした');profile={...profile,...payload};toast('設定を保存しました ♡');renderHome()};
$('#shuffleRecommendations').onclick=renderRecommendations;$('#recapYear').onchange=renderRecap;$('#recapMonth').onchange=renderRecap;

function escapeHtml(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
bootstrap();
