(()=>{const R=[['any','誰とでも','✨'],['couple','恋人・夫婦','💗'],['friend','友達','👬'],['first','初対面','🤝'],['family','家族','🏠'],['party','飲み会・グループ','🥂']],C=[['fun','盛り上がる','😂'],['know','相手を知る','🔎'],['deep','深い話','🌙'],['love','恋愛','💗'],['memory','思い出','📷'],['future','未来','✨'],['choice','もしも・二択','⚖️'],['food','食べ物','🍽️'],['travel','旅行','✈️'],['work','仕事・勉強','💻'],['group','グループ','🎉']],D={light:'軽め',medium:'ほどよく',deep:'深め'},S={f:'hanashi_favorites_v1',h:'hanashi_history_v1',s:'hanashi_settings_v1',n:'hanashi_shown_v1'},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],g=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},p=(k,v)=>localStorage.setItem(k,JSON.stringify(v));let st=Object.assign({relation:'any',categories:[],depth:'all'},g(S.s,{})),fav=g(S.f),hist=g(S.h),shown=g(S.n),cur=null,pool=[],seen=new Set(),mode='favorites';
const match=t=>(st.relation==='any'||t.relations.includes(st.relation)||t.relations.includes('any'))&&(!st.categories.length||st.categories.includes(t.category))&&(st.depth==='all'||(st.depth==='light'?t.depth!=='deep':t.depth!=='light'));
function filters(){$('#relationChips').innerHTML=R.map(x=>'<button data-relation="'+x[0]+'" class="'+(st.relation===x[0]?'active':'')+'">'+x[2]+' '+x[1]+'</button>').join('');$('#categoryChips').innerHTML=C.map(x=>'<button data-category="'+x[0]+'" class="'+(st.categories.includes(x[0])?'active':'')+'">'+x[2]+' '+x[1]+'</button>').join('');$$('#depthControl button').forEach(b=>b.classList.toggle('active',st.depth===b.dataset.depth));$('#favoriteCount').textContent=fav.length;$('#topicCount').textContent=TOPICS.length+'件';pool=TOPICS.filter(match);$('#poolNote').textContent=pool.length+'件の話題からランダムに選びます'}
function save(){p(S.s,st);filters()} function view(v){$('#mainView').classList.toggle('hidden',v!=='home');$('#topicScreen').classList.toggle('hidden',v!=='topic');$('#listScreen').classList.toggle('hidden',v!=='list');scrollTo({top:0,behavior:'smooth'})}
function toast(m){let e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1600)}
function pick(){pool=TOPICS.filter(match);if(!pool.length)return toast('条件に合う話題がありません');let a=pool.filter(t=>!seen.has(t.id)&&!shown.includes(t.id));if(!a.length)a=pool.filter(t=>!seen.has(t.id));if(!a.length){seen.clear();a=pool}cur=a[Math.floor(Math.random()*a.length)];seen.add(cur.id);shown=[cur.id,...shown.filter(x=>x!==cur.id)].slice(0,250);p(S.n,shown);render();view('topic')}
function render(){let rl=R.find(x=>x[0]===st.relation)?.[1]||'誰とでも';$('#topicMeta').innerHTML='<span class="meta-pill accent">'+cur.categoryLabel+'</span><span class="meta-pill">'+D[cur.depth]+'</span><span class="meta-pill">'+rl+'</span>';$('#topicText').textContent=cur.text;let f=fav.includes(cur.id),h=hist.includes(cur.id);$('#favoriteTopicBtn').classList.toggle('active',f);$('#favoriteTopicBtn').innerHTML='<span>'+(f?'♥':'♡')+'</span> '+(f?'保存済み':'お気に入り');$('#doneTopicBtn').classList.toggle('active',h);$('#doneTopicBtn').innerHTML='<span>✓</span> '+(h?'話した！':'話した');$('#expandPanel').classList.add('hidden');$('#expandBtn').classList.remove('hidden');$('#progressBar').style.width=Math.max(4,Math.min(100,seen.size/Math.max(1,pool.length)*100))+'%';$('#remainingNote').textContent='この条件では約'+pool.length+'件の話題があります'}
function openList(m){mode=m;$('#listTitle').textContent=m==='favorites'?'お気に入り':'話した履歴';list();view('list')} function list(){let ids=mode==='favorites'?fav:hist,a=ids.map(i=>TOPICS.find(t=>t.id===i)).filter(Boolean);$('#listContent').innerHTML=a.length?a.map(t=>'<div class="saved-card"><div><p>'+t.text+'</p><small>'+t.categoryLabel+'・'+D[t.depth]+'</small></div><button data-remove-id="'+t.id+'">×</button></div>').join(''):'<div class="empty-state"><div class="emoji">'+(mode==='favorites'?'♡':'◷')+'</div><h3>まだ何もありません</h3><p>気になる話題を保存できます。</p></div>'}
$('#relationChips').onclick=e=>{let b=e.target.closest('[data-relation]');if(b){st.relation=b.dataset.relation;save()}};$('#categoryChips').onclick=e=>{let b=e.target.closest('[data-category]');if(b){let c=b.dataset.category;st.categories=st.categories.includes(c)?st.categories.filter(x=>x!==c):[...st.categories,c];save()}};$('#depthControl').onclick=e=>{let b=e.target.closest('[data-depth]');if(b){st.depth=b.dataset.depth;save()}};
$('#startBtn').onclick=$('#nextBtn').onclick=pick;$('#backBtn').onclick=$('#brandBtn').onclick=$('#listBackBtn').onclick=()=>{filters();view('home')};$('#favoritesBtn').onclick=()=>openList('favorites');$('#historyBtn').onclick=()=>openList('history');
$('#favoriteTopicBtn').onclick=()=>{if(fav.includes(cur.id)){fav=fav.filter(x=>x!==cur.id);toast('お気に入りから外しました')}else{fav.unshift(cur.id);toast('お気に入りに保存しました')}p(S.f,fav);$('#favoriteCount').textContent=fav.length;render()};$('#doneTopicBtn').onclick=()=>{if(hist.includes(cur.id))hist=hist.filter(x=>x!==cur.id);else hist=[cur.id,...hist].slice(0,200);p(S.h,hist);render()};
$('#copyTopicBtn').onclick=async()=>{try{await navigator.clipboard.writeText(cur.text);toast('話題をコピーしました')}catch{toast('コピーできませんでした')}};$('#shuffleSettingsBtn').onclick=()=>{st={relation:'any',categories:[],depth:'all'};save();pick()};$('#expandBtn').onclick=()=>{let a=TOPICS.filter(t=>t.id!==cur.id&&t.category===cur.category&&match(t)).sort(()=>Math.random()-.5).slice(0,3);$('#relatedQuestions').innerHTML=a.map(t=>'<button class="related-item" data-topic-id="'+t.id+'">→ '+t.text+'</button>').join('');$('#expandPanel').classList.remove('hidden');$('#expandBtn').classList.add('hidden')};$('#relatedQuestions').onclick=e=>{let b=e.target.closest('[data-topic-id]');if(b){cur=TOPICS.find(t=>t.id===+b.dataset.topicId);render()}};
$('#listContent').onclick=e=>{let b=e.target.closest('[data-remove-id]');if(!b)return;let id=+b.dataset.removeId;if(mode==='favorites'){fav=fav.filter(x=>x!==id);p(S.f,fav);$('#favoriteCount').textContent=fav.length}else{hist=hist.filter(x=>x!==id);p(S.h,hist)}list()};$('#clearListBtn').onclick=()=>{if(mode==='favorites'){fav=[];p(S.f,[]);$('#favoriteCount').textContent=0}else{hist=[];p(S.h,[])}list();toast('すべて削除しました')};$$('.quick-card').forEach(b=>b.onclick=()=>{let q=b.dataset.quick;st={relation:q==='love'?'couple':'any',categories:[q],depth:q==='deep'?'deep':'all'};p(S.s,st);pick()});filters()})();